<?php

namespace App\Console\Commands;

use App\Enums\PermissionEnum;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

/**
 * Artisan command that syncs PermissionEnum definitions into the database.
 */
/**
 * Artisan command to sync PermissionEnum cases to the database and TypeScript enum.
 */
class SyncPermissionsCommand extends Command
{
    protected $signature = 'permissions:sync {--prune : Remove permissions that are no longer defined in PermissionEnum}';

    protected $description = 'Sync PermissionEnum cases to the database and generate TypeScript enum';

    /**
     * Execute the command.
     */

    /**
     * Sync PermissionEnum cases to the database and regenerate the TypeScript enum.
     */
    public function handle(): int
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $guard = config('auth.defaults.guard', 'web');
        $enumValues = PermissionEnum::values();

        foreach ($enumValues as $name) {
            Permission::query()->firstOrCreate(
                ['name' => $name, 'guard_name' => $guard],
            );
        }

        $this->info(sprintf('Synced %d permissions.', count($enumValues)));

        if ($this->option('prune')) {
            $deleted = Permission::query()
                ->where('guard_name', $guard)
                ->whereNotIn('name', $enumValues)
                ->delete();

            $this->info(sprintf('Pruned %d stale permissions.', $deleted));
        }

        $this->generateTypeScriptEnum();
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        return self::SUCCESS;
    }

    /**
     * Write the generated PermissionEnum TypeScript file to resources/js/enums.
     */
    protected function generateTypeScriptEnum(): void
    {
        $lines = [
            '/**',
            ' * Auto-generated by `php artisan permissions:sync`. Do not edit manually.',
            ' */',
            'export enum PermissionEnum {',
        ];

        foreach (PermissionEnum::cases() as $case) {
            $lines[] = sprintf("    %s = '%s',", $case->name, $case->value);
        }

        $lines[] = '}';
        $lines[] = '';
        $lines[] = '/** @deprecated Use PermissionEnum — kept for backwards compatibility */';
        // ponytail: match Prettier printWidth so permissions:sync does not fail format:check
        $lines[] = 'export const PermissionEnumValues = Object.values(';
        $lines[] = '    PermissionEnum,';
        $lines[] = ') as PermissionEnum[];';
        $lines[] = '';

        $path = resource_path('js/enums/permission-enum.ts');
        File::ensureDirectoryExists(dirname($path));
        File::put($path, implode(PHP_EOL, $lines));

        $this->info("Generated {$path}");
    }
}
