/**
 * Auto-generated by `php artisan permissions:sync`. Do not edit manually.
 */
export enum PermissionEnum {
    CanShowUsers = 'can-show-users',
    CanCreateUsers = 'can-create-users',
    CanEditUsers = 'can-edit-users',
    CanDeleteUsers = 'can-delete-users',
    CanRestoreUsers = 'can-restore-users',
    CanForceDeleteUsers = 'can-force-delete-users',
    CanShowGroups = 'can-show-groups',
    CanCreateGroups = 'can-create-groups',
    CanEditGroups = 'can-edit-groups',
    CanDeleteGroups = 'can-delete-groups',
    CanRestoreGroups = 'can-restore-groups',
    CanForceDeleteGroups = 'can-force-delete-groups',
    CanShowRoles = 'can-show-roles',
    CanCreateRoles = 'can-create-roles',
    CanEditRoles = 'can-edit-roles',
    CanDeleteRoles = 'can-delete-roles',
    CanShowPermissions = 'can-show-permissions',
    CanCreatePermissions = 'can-create-permissions',
    CanEditPermissions = 'can-edit-permissions',
    CanDeletePermissions = 'can-delete-permissions',
    CanShowFiles = 'can-show-files',
    CanCreateFiles = 'can-create-files',
    CanEditFiles = 'can-edit-files',
    CanDeleteFiles = 'can-delete-files',
    CanRestoreFiles = 'can-restore-files',
    CanForceDeleteFiles = 'can-force-delete-files',
    CanShowCollections = 'can-show-collections',
    CanCreateCollections = 'can-create-collections',
    CanEditCollections = 'can-edit-collections',
    CanDeleteCollections = 'can-delete-collections',
    CanRestoreCollections = 'can-restore-collections',
    CanForceDeleteCollections = 'can-force-delete-collections',
}

/** @deprecated Use PermissionEnum — kept for backwards compatibility */
export const PermissionEnumValues = Object.values(PermissionEnum) as PermissionEnum[];
